//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.23 at 11:00:08 AM CEST 
//


package com.rightpoint.adobe.assets.configuration.elem;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adobe.scene7.migration.configuration.elem package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adobe.scene7.migration.configuration.elem
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServerConfiguration }
     * 
     */
    public ServerConfiguration createServerConfiguration() {
        return new ServerConfiguration();
    }

    /**
     * Create an instance of {@link FolderConfiguration }
     *
     */
    public FolderConfiguration createFolderConfiguration() {
        return new FolderConfiguration();
    }
}
